"""RAG docs-assistant endpoints.

Answers questions about FreeInference using the public user docs as a knowledge
base. Both halves route through the gateway itself:

* the **query** is embedded with the in-process embedding adapter (``bge-m3``),
* the **answer** is generated by the routing engine (``RouteExecutor``).

The vector index is built offline by ``python -m serving.rag.ingest`` and loaded
lazily from disk here (cached, with mtime-based invalidation).

Auth uses ``get_current_user`` (JWT) — the same dependency the dashboard uses —
so the Next.js chat page can call it with the session token it already holds.
"""

from __future__ import annotations

import json
from contextlib import suppress
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from serving.rag.config import load_rag_settings
from serving.rag.embedder import HashEmbedder
from serving.rag.pipeline import build_messages, sources_payload
from serving.rag.store import VectorStore
from serving.servers.deps import get_current_user, get_embedding_adapters, get_router
from serving.stream import make_role_chunk
from serving.utils.logging import get_logger

logger = get_logger(__name__)
router = APIRouter(prefix="/v1/rag", tags=["RAG"])

# Internal routing metadata that must never reach the client (mirrors playground).
_INTERNAL_KEYS = frozenset({"_routing"})

# Lazily-loaded index, cached across requests and invalidated when the file's
# mtime changes so a re-ingest is picked up without a restart.
_store: VectorStore | None = None
_store_path: str | None = None
_store_mtime: float | None = None


def _load_store() -> VectorStore | None:
    """Return the cached index, (re)loading from disk when needed."""
    global _store, _store_path, _store_mtime
    settings = load_rag_settings()
    path = settings.index_path
    if not path.exists():
        _store = None
        _store_path = None
        _store_mtime = None
        return None
    mtime = path.stat().st_mtime
    if _store is None or _store_path != str(path) or _store_mtime != mtime:
        try:
            loaded = VectorStore.load(path)
        except Exception as exc:
            # A concurrent/partial re-ingest can momentarily yield an unparseable
            # file; keep serving the previously loaded index rather than 500.
            logger.warning(f"failed to load rag index at {path}: {exc}")
            return _store
        _store = loaded
        _store_path = str(path)
        _store_mtime = mtime
        logger.info(
            "rag_index_loaded",
            extra={"path": str(path), "chunks": len(_store.records), "model": _store.embed_model},
        )
    return _store


class RagMessage(BaseModel):
    """One chat turn."""

    role: str
    content: str


class RagChatRequest(BaseModel):
    """Request body for the RAG chat endpoint."""

    messages: list[RagMessage] = Field(..., min_length=1)
    model: str | None = None
    top_k: int | None = Field(default=None, ge=1, le=20)
    stream: bool = True


def _sanitize_chunk(chunk: str) -> str:
    """Strip internal routing metadata from an SSE chunk before sending."""
    if not chunk.startswith("data: ") or chunk.startswith("data: [DONE]"):
        return chunk
    try:
        obj = json.loads(chunk[6:])
        changed = False
        for key in _INTERNAL_KEYS:
            if key in obj:
                del obj[key]
                changed = True
        if changed:
            return f"data: {json.dumps(obj)}\n\n"
    except Exception:
        pass
    return chunk


async def _embed_query(
    store: VectorStore, query: str, embedding_adapters: dict[str, Any]
) -> list[float]:
    """Embed ``query`` with an embedder matching the one that built the index."""
    if store.embedder_mode == "hash":
        return HashEmbedder(dim=store.dim, model=store.embed_model).embed_query(query)

    adapter = embedding_adapters.get(store.embed_model)
    if adapter is None:
        raise HTTPException(
            status_code=503,
            detail=(
                f"Embedding model '{store.embed_model}' is not available on this "
                "gateway, so the query can't be embedded."
            ),
        )
    try:
        response = await adapter.embeddings(query)
    except HTTPException:
        raise
    except Exception as exc:
        # Upstream/key-pool/transport failure — surface a graceful 503 rather than
        # an opaque 500 (which, mid-stream, would break before the first SSE byte).
        logger.warning(f"rag query embedding failed via '{store.embed_model}': {exc}")
        raise HTTPException(
            status_code=503, detail="Embedding service temporarily unavailable."
        ) from exc
    try:
        vector = [float(x) for x in response["data"][0]["embedding"]]
    except (KeyError, IndexError, TypeError, ValueError) as exc:
        raise HTTPException(status_code=502, detail="Malformed embedding response") from exc
    if not vector:
        raise HTTPException(status_code=502, detail="Malformed embedding response")
    return vector


@router.get("/status")
async def rag_status() -> dict[str, Any]:
    """Report whether the index is built and which models it uses."""
    settings = load_rag_settings()
    store = _load_store()
    return {
        "index_loaded": store is not None,
        "num_chunks": len(store.records) if store else 0,
        "embed_model": store.embed_model if store else settings.embed_model,
        "embedder_mode": store.embedder_mode if store else settings.embedder_mode,
        "chat_model": settings.chat_model,
        "index_path": str(settings.index_path),
    }


@router.post("/chat")
async def rag_chat(
    body: RagChatRequest,
    _user: dict[str, Any] = Depends(get_current_user),
    router_exec=Depends(get_router),
    embedding_adapters: dict[str, Any] = Depends(get_embedding_adapters),
) -> Any:
    """Answer the latest user question, grounded in retrieved docs."""
    settings = load_rag_settings()
    store = _load_store()
    if store is None:
        raise HTTPException(
            status_code=503,
            detail="RAG index not built. Run `python -m serving.rag.ingest` first.",
        )

    # The query is the most recent user turn; history is every turn strictly
    # before it, so the query is never duplicated into history when the request
    # ends with a non-user (assistant/system) turn.
    query_idx = next(
        (i for i in range(len(body.messages) - 1, -1, -1) if body.messages[i].role == "user"),
        None,
    )
    if query_idx is None:
        raise HTTPException(status_code=400, detail="No user message to answer.")
    query = body.messages[query_idx].content.strip()
    if not query:
        raise HTTPException(status_code=400, detail="Empty user message.")
    history = [m.model_dump() for m in body.messages[:query_idx]]

    query_vec = await _embed_query(store, query, embedding_adapters)
    if store.dim and len(query_vec) != store.dim:
        # Fail loud instead of letting cosine_similarity silently return 0.0 for
        # every record (which would yield plausible-looking but garbage sources).
        raise HTTPException(
            status_code=502,
            detail=(
                f"Query embedding dimension {len(query_vec)} does not match index "
                f"dimension {store.dim}; rebuild the index."
            ),
        )
    top_k = body.top_k or settings.top_k
    results = store.search(query_vec, top_k)
    messages = build_messages(query, results, history)
    sources = sources_payload(results)
    model = body.model or settings.chat_model
    gen_kwargs = {"temperature": settings.temperature, "max_tokens": settings.max_tokens}

    if not body.stream:
        response = await router_exec.chat_completion(model, messages, **gen_kwargs)
        with suppress(Exception):
            response.pop("_routing", None)
        answer = ""
        with suppress(Exception):
            answer = response["choices"][0]["message"]["content"]
        return {"answer": answer, "sources": sources, "model": model}

    async def _generate():
        # Emit retrieved sources first so the UI can render citations before the
        # answer streams in, then the model's OpenAI-format SSE chunks.
        yield f"data: {json.dumps({'type': 'sources', 'sources': sources})}\n\n"
        yield make_role_chunk(model=model)
        async for chunk in router_exec.stream_chat_completion(model, messages, **gen_kwargs):
            with suppress(Exception):
                chunk = _sanitize_chunk(chunk)
            yield chunk

    return StreamingResponse(
        _generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "X-Accel-Buffering": "no",
        },
    )
