'use strict';

/**
 * Which public-site UI this build compiles in.
 *
 * The default is the neutral UI in `src/site-ui/neutral`. A distribution points
 * `SITE_UI_DIR` (plus `SITE_UI_API`) at a directory of its own and the build
 * compiles that instead, through the same `@site-ui` specifier.
 *
 * ## The rule that matters
 *
 * *Absent* extension means the neutral UI. *Present but broken* extension stops
 * the build. There is no third state: a typo in a path, a module written for a
 * different interface revision and a module that simply forgot to export
 * `Landing` all have to fail loudly, because the alternative is publishing a
 * site whose home page or sign-in frame silently reverted to a design nobody
 * asked for.
 *
 * ## Why this file is plain CommonJS and not TypeScript
 *
 * Three toolchains have to agree on one answer: Next/Webpack, TypeScript and
 * Vitest. Next loads its config once, at the start of every command, in plain
 * Node. Keeping the resolution logic here — the single place that decides —
 * means the generator, the config and the test runner cannot drift apart the
 * way three copies of an alias would.
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const fs = require('node:fs');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const path = require('node:path');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { verifyModuleImports } = require('./verify-imports');

/** Interface revision this checkout implements. */
const SITE_UI_API_VERSION = 1;

/** Environment variables a distribution sets to compile in its own UI. */
const SITE_UI_DIR_ENV = 'SITE_UI_DIR';
const SITE_UI_API_ENV = 'SITE_UI_API';

/** Sub-paths a distribution's UI directory must provide. */
const CLIENT_ENTRY = 'client';
const SERVER_ENTRY = 'server';
const STYLES_ENTRY = 'styles.css';

/** Generated artefacts, all inside the frontend directory and all gitignored. */
const GENERATED_DIR = path.posix.join('src', 'generated', 'distribution-ui');
const NEUTRAL_DIR = path.posix.join('src', 'site-ui', 'neutral');

/**
 * The one specifier the application imports, and the bridge that satisfies it.
 *
 * `@site-ui` always resolves to this directory — in `tsconfig.json`, in the
 * bundler alias and in Vitest — and the generated `index.ts` inside it decides
 * what that means. Keeping one stable specifier is what lets the three
 * toolchains share a single answer without three copies of a path.
 */
const BRIDGE_DIR = path.posix.join('src', 'site-ui', 'active');
const STUB_FILE = path.posix.join(BRIDGE_DIR, 'client.ts');
const MANIFEST_FILE = path.posix.join(GENERATED_DIR, 'manifest.json');
const TSCONFIG_FILE = 'tsconfig.generated.json';

/** First line of every generated file: a human who opens one should know. */
const GENERATED_BANNER = '// @generated by apps/frontend/src/site-ui/resolve.js — do not edit.\n';

class SiteUiConfigError extends Error {
  constructor(message) {
    super(message);
    this.name = 'SiteUiConfigError';
  }
}

/**
 * Read the extension request from an environment.
 *
 * `env.SITE_UI_DIR` set to whitespace or to the empty string is *not* a
 * request — shells and CI systems hand those out for unset variables all the
 * time — so it is treated as absent.
 */
function readSiteUiRequest(env) {
  const rawDir = (env[SITE_UI_DIR_ENV] || '').trim();
  if (rawDir === '') return { kind: 'neutral' };

  const rawApi = (env[SITE_UI_API_ENV] || '').trim();
  if (rawApi === '') {
    throw new SiteUiConfigError(
      `${SITE_UI_DIR_ENV} is set to ${rawDir} but ${SITE_UI_API_ENV} is not. ` +
        `Set ${SITE_UI_API_ENV}=${SITE_UI_API_VERSION} to state which Site UI API ` +
        'revision the module implements.',
    );
  }

  const api = Number(rawApi);
  if (!Number.isInteger(api)) {
    throw new SiteUiConfigError(
      `${SITE_UI_API_ENV} must be an integer, got ${JSON.stringify(rawApi)}.`,
    );
  }
  if (api !== SITE_UI_API_VERSION) {
    throw new SiteUiConfigError(
      `This checkout implements Site UI API v${SITE_UI_API_VERSION}; ` +
        `the configured module declares v${api}. Upgrade one of the two rather ` +
        'than building a module against an interface it was not written for.',
    );
  }

  const absolute = path.resolve(rawDir);
  const entries = {
    client: path.join(absolute, CLIENT_ENTRY),
    server: path.join(absolute, SERVER_ENTRY),
    styles: path.join(absolute, STYLES_ENTRY),
  };

  for (const [name, base] of Object.entries(entries)) {
    const exists =
      name === 'styles'
        ? isFile(base) || isFile(`${base}.css`)
        : isFile(`${base}.tsx`) || isFile(`${base}.ts`) || isFile(`${base}.jsx`);
    if (!exists) {
      throw new SiteUiConfigError(
        `${SITE_UI_DIR_ENV} points at ${absolute}, which has no ${CLIENT_ENTRY}/${SERVER_ENTRY}/` +
          `${STYLES_ENTRY} set: the ${name} entry is missing. Expected ` +
          `${CLIENT_ENTRY}.tsx, ${SERVER_ENTRY}.ts and ${STYLES_ENTRY}.`,
      );
    }
  }

  return { kind: 'distribution', root: absolute, api };
}

function isFile(candidate) {
  try {
    return fs.statSync(candidate).isFile();
  } catch {
    return false;
  }
}

/**
 * Resolve the absolute entry paths for the active configuration.
 *
 * `frontendDir` is `apps/frontend`; the returned paths are used verbatim as
 * bundler aliases, so they are absolute.
 */
function resolveSiteUi(frontendDir, env = process.env) {
  // Normalized here rather than trusted from the caller: these paths become
  // bundler aliases and the generated stub's import specifiers, and a relative
  // `frontendDir` would silently produce specifiers that resolve against the
  // stub's own directory instead of the project root.
  frontendDir = path.resolve(frontendDir);
  const request = readSiteUiRequest(env);

  if (request.kind === 'neutral') {
    const neutral = path.join(frontendDir, NEUTRAL_DIR);
    return {
      kind: 'neutral',
      id: 'neutral',
      api: SITE_UI_API_VERSION,
      root: neutral,
      moduleDir: neutral,
      client: path.join(neutral, `${CLIENT_ENTRY}.tsx`),
      server: path.join(neutral, `${SERVER_ENTRY}.ts`),
      styles: path.join(neutral, STYLES_ENTRY),
      stub: path.join(frontendDir, STUB_FILE),
      manifestPath: path.join(frontendDir, MANIFEST_FILE),
      tsconfigPath: path.join(frontendDir, TSCONFIG_FILE),
    };
  }

  return {
    kind: 'distribution',
    id: descriptorId(request.root) ?? path.basename(request.root),
    api: request.api,
    root: request.root,
    moduleDir: request.root,
    client: resolveEntry(request.root, CLIENT_ENTRY),
    server: resolveEntry(request.root, SERVER_ENTRY),
    styles: resolveStyles(request.root),
    stub: path.join(frontendDir, STUB_FILE),
    manifestPath: path.join(frontendDir, MANIFEST_FILE),
    tsconfigPath: path.join(frontendDir, TSCONFIG_FILE),
  };
}

/** Read a literal descriptor without executing a module's client code. */
function readDescriptor(moduleDir) {
  // TypeScript is already a locked build dependency. Its parser supports type
  // annotations, `as const` and `satisfies` without mistaking comments for code.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const ts = require('typescript');
  const entry = resolveEntry(moduleDir, CLIENT_ENTRY);
  const source = ts.createSourceFile(
    entry,
    fs.readFileSync(entry, 'utf8'),
    ts.ScriptTarget.Latest,
    true,
  );
  for (const statement of source.statements) {
    if (
      !ts.isVariableStatement(statement) ||
      !statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword)
    )
      continue;
    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== 'descriptor') continue;
      let value = declaration.initializer;
      while (
        value &&
        (ts.isAsExpression(value) ||
          ts.isSatisfiesExpression(value) ||
          ts.isParenthesizedExpression(value))
      ) {
        value = value.expression;
      }
      if (!value || !ts.isObjectLiteralExpression(value)) break;
      const result = {};
      for (const property of value.properties) {
        if (!ts.isPropertyAssignment(property)) continue;
        const key = property.name.text;
        const literal = property.initializer;
        if (ts.isStringLiteral(literal) || ts.isNumericLiteral(literal)) {
          result[key] = ts.isNumericLiteral(literal) ? Number(literal.text) : literal.text;
        }
      }
      return result;
    }
  }
  throw new SiteUiConfigError(
    'descriptor must be an exported object literal with id, siteUiApi and locale',
  );
}

function descriptorId(moduleDir) {
  try {
    return readDescriptor(moduleDir).id;
  } catch {
    // Missing/invalid entries receive actionable errors in assertSiteUiEntries.
    return undefined;
  }
}

/**
 * The real file behind an entry name.
 *
 * `require.resolve` is deliberately not used: it does not resolve TypeScript
 * extensions, and a module written in `.tsx` would then fail to be found by a
 * check whose whole purpose is to find it.
 */
function resolveEntry(root, name) {
  for (const extension of ['.tsx', '.ts', '.jsx', '.js']) {
    const candidate = path.join(root, `${name}${extension}`);
    if (isFile(candidate)) return candidate;
  }
  return path.join(root, `${name}.tsx`);
}

function resolveStyles(root) {
  const exact = path.join(root, STYLES_ENTRY);
  return isFile(exact) ? exact : `${exact}.css`;
}

/**
 * The bundler alias for both specifiers.
 *
 * `@site-ui` is what client components use; `@site-ui-server` is what server
 * code uses. They resolve to the same generated module — the difference is
 * which export the importer takes — but keeping two names lets a mistaken
 * import in the wrong environment read as a mistake.
 */
function webpackAlias(frontendDir, resolution) {
  const bridge = path.dirname(resolution.stub);
  return {
    // What the application uses.
    '@site-ui/client': path.join(bridge, 'client'),
    '@site-ui/server': path.join(bridge, 'server'),
    // What a *module* uses. Pointed at the facade file rather than at the
    // module directory, so a distribution writes one import that cannot drift
    // with the host's layout, and so the module never needs to know where in
    // this repository the facade lives.
    '@site-ui/host': path.join(frontendDir, 'src', 'site-ui', 'host'),
  };
}

/** The Vitest resolver has to point at the same file the bundler does. */
function vitestAlias(frontendDir, resolution) {
  return webpackAlias(frontendDir, resolution);
}

/**
 * The re-export stubs the `@site-ui` and `@site-ui-server` specifiers point at.
 *
 * They are generated, never hand-edited, and gitignored: they are a view of the
 * resolution, not source files. Two specifiers rather than one because the
 * client module is a component tree and the server module is plain data — a
 * server component that imported the combined entry would drag `usePathname`
 * into a module with no request.
 *
 * Static `export … from` statements and not computed requires, so the bundler
 * sees a normal module with normal static dependencies and can tree-shake and
 * code-split it.
 */
/**
 * The three files the bridge directory needs.
 *
 * `client.ts` and `server.ts` forward to the active module; `styles.css` does
 * the same for its stylesheet. Written as three small files rather than one
 * barrel because `tsc` will not resolve a directory specifier to an index file,
 * and the bridge has to be legible to `tsc` as well as to Webpack.
 */
function bridgeSources(resolution) {
  // Extensionless, for the bundler's `resolve.extensions` to complete. These
  // files are never type-checked — `tsconfig.generated.json` maps the specifiers
  // straight at the module — so they only have to satisfy Webpack's resolver.
  //
  // `path.dirname`, not a join with `..`: joining resolves the `..` against the
  // stub's own filename and climbs one level too far.
  const relative = (target) => {
    const parsed = path.parse(path.relative(path.dirname(resolution.stub), target));
    const withoutExtension = path.join(parsed.dir, parsed.name);
    return JSON.stringify(withoutExtension.split(path.sep).join(path.posix.sep));
  };

  return {
    'client.ts': `${GENERATED_BANNER}export * from ${relative(resolution.client)};\n`,
    // Named, not `export *`, and the difference is the point. `SiteUiServerModule`
    // documents two *optional* fields, and the console's layout imports one of
    // them unconditionally — so a module that declares neither, which is the
    // common case and the one the example module takes, failed to type-check
    // against a contract that said both were optional. A module is not required
    // to state a language it does not have an opinion about.
    //
    // Re-exporting the two documented fields with their defaults is what makes
    // the documented optionality real. A module's other server exports are
    // dropped rather than forwarded: the interface is two fields, and forwarding
    // an undeclared one would let a capability reach the host without the
    // contract ever describing it.
    // A namespace import plus a documented default, because the interface's
    // server half is two *optional* fields and TypeScript cannot read a field
    // that may not be declared: `module_.locale ?? ''` is an error when the
    // module declares no locale, which would make the optionality true on paper
    // and false in the build.
    //
    // The probe is a cast rather than a typed read for exactly that reason, and
    // it is narrow on purpose: `metadata` and `locale` are the whole interface,
    // and a module whose server entry declares neither is the common case — the
    // example module is one. Everything else the module exports passes through
    // `export *` untouched.
    'server.ts':
      `${GENERATED_BANNER}import * as module_ from ${relative(resolution.server)};\n` +
      `export * from ${relative(resolution.server)};\n` +
      'const optional = module_ as unknown as { locale?: string; metadata?: unknown };\n' +
      "export const locale: string = optional.locale ?? '';\n" +
      'export const metadata = optional.metadata;\n',
    'styles.css': `/* Auto-generated by src/site-ui/resolve.js — do not edit. */\n@import ${relative(
      resolution.styles,
    )};\n`,
  };
}

function manifestSource(resolution) {
  // Four fields, and no filesystem path among them.
  //
  // This file travels: it is copied into the container so a running image can
  // be asked what it contains rather than trusted to have been labelled. Paths
  // do not survive that trip — an earlier version recorded them relative to the
  // generated bridge, so a distributed image named the builder's scratch
  // directory: a path that describes one machine and nothing a reader can act
  // on. What identifies a build is the module's own name and the interface
  // revision it implements, and those are stable wherever the build ran.
  return `${JSON.stringify(
    {
      site_ui_api: resolution.api,
      kind: resolution.kind,
      id: resolution.id,
      module: path.basename(resolution.moduleDir),
    },
    null,
    2,
  )}\n`;
}

/**
 * A TypeScript project that adds the generated declarations to the app's own.
 *
 * Type-checking is the third toolchain that has to see the *same* module the
 * bundler will compile. An alias alone would leave `tsc` checking the neutral
 * UI while the build shipped the distribution's, which is exactly the
 * disagreement this file exists to prevent.
 *
 * `include` is repeated rather than inherited: in a TypeScript config it
 * replaces the base value instead of adding to it, and dropping `.next/types`
 * would silently stop checking whether the pages Next generates still match.
 */
function tsconfigSource(frontendDir, baseTsconfig, resolution) {
  // `paths` entries resolve against `baseUrl`, which is the frontend directory
  // (`.`) in both projects, so every target is relative to it. That matters
  // more than it looks: `tsc` resolves `@site-ui` to a *directory*, and a bare
  // absolute path there is not a valid `paths` value.
  // The app's own mappings are repeated here because `paths` replaces rather
  // than merges: an extension that declared only `@site-ui` would silently drop
  // `@/*` and every import in the application would stop resolving.
  // Concrete files, not the bridge directory. `tsc` does not resolve a folder
  // specifier to `index.ts` the way Webpack does, and a `paths` entry pointing
  // at a directory would leave the type checker unable to see the module the
  // bundler actually compiles — the exact disagreement this resolver exists to
  // prevent. The bridge is still generated, because Webpack needs a real entry
  // to follow; TypeScript simply never has to go through it.
  const relative = (target) =>
    path.relative(frontendDir, target).split(path.sep).join(path.posix.sep);

  const paths = {
    ...(baseTsconfig.compilerOptions?.paths ?? {}),
    '@site-ui/client': [relative(resolution.client)],
    '@site-ui/server': [relative(resolution.server)],
    '@site-ui/host': [path.posix.join('src', 'site-ui', 'host')],
  };

  return `${JSON.stringify(
    {
      extends: './tsconfig.json',
      compilerOptions: { baseUrl: '.', paths },
      include: baseTsconfig.include,
      // The staging directory is a build input the *composer* writes inside
      // this checkout, so it must not be type-checked as part of this project.
      //
      // It is not merely redundant: the staged module resolves `react` and
      // `next` from the shared install by walking up from its own path, and a
      // copy placed under `apps/frontend` is reached through a link whose real
      // path is outside the checkout, so the walk finds nothing. Webpack is
      // unaffected (Next resolves modules from the project root), which is why
      // the symptom is type errors on a build that compiles perfectly.
      //
      // The same directory is on `.gitignore`, for the same reason: it is the
      // composer's, not this repository's.
      exclude: [...baseTsconfig.exclude, '.distribution-ui', '.distribution-ui/tests'],
    },
    null,
    2,
  )}\n`;
}

function readBaseTsconfig(frontendDir) {
  const file = path.join(frontendDir, 'tsconfig.json');
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

/**
 * Write the generated artefacts and return the resolution.
 *
 * Idempotent: a second call with the same environment writes byte-identical
 * files, so a build is not "dirty" merely because it ran twice.
 */
function generateSiteUi(frontendDir, env = process.env) {
  const resolution = resolveSiteUi(frontendDir, env);

  const bridgeDir = path.dirname(path.join(frontendDir, STUB_FILE));
  for (const [name, contents] of Object.entries(bridgeSources(resolution))) {
    write(path.join(bridgeDir, name), contents);
  }
  write(path.join(frontendDir, MANIFEST_FILE), manifestSource(resolution));
  write(
    path.join(frontendDir, TSCONFIG_FILE),
    tsconfigSource(frontendDir, readBaseTsconfig(frontendDir), resolution),
  );

  return resolution;
}

function write(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents);
}

/**
 * Generate, then check that the active module can actually be compiled.
 *
 * Generation alone is not enough. A module can resolve and still be missing an
 * export, or declare an API revision it does not implement, and both of those
 * have to stop the build here rather than surface as a blank page in
 * production. The entries are loaded through the same `require` the bundler's
 * resolver would use, so this checks the file the build will read.
 */
function prepareSiteUi(frontendDir, env = process.env) {
  const resolution = generateSiteUi(frontendDir, env);
  assertModulePresent(resolution);
  assertSiteUiEntries(resolution);
  assertModuleImports(resolution);
  return resolution;
}

/**
 * Refuse a configuration whose module has gone away.
 *
 * The staging directory a composer uses is deleted when its build finishes, so
 * a checkout can be left with a bridge pointing at nothing. TypeScript then
 * reports four "cannot find module" errors naming `@site-ui/client`,
 * `@site-ui/server` and the staging path — which reads like a broken
 * application rather than a stale build artefact, and is exactly the confusion
 * the explicit prepare step exists to remove.
 */
function assertModulePresent(resolution) {
  for (const [label, file] of [
    ['client entry', resolution.client],
    ['server entry', resolution.server],
    ['stylesheet', resolution.styles],
  ]) {
    if (!isFile(file)) {
      throw new SiteUiConfigError(
        `the configured Site UI's ${label} is missing: ${file}. ${
          resolution.kind === 'distribution'
            ? 'A staging directory is deleted when the build that created it finishes; ' +
              're-run the composer rather than pointing SITE_UI_DIR at a stale path.'
            : 'This checkout is incomplete.'
        }`,
      );
    }
  }
}

/**
 * The module may only import the host facade, the framework and its own files.
 *
 * Checked at build time rather than in review because a forbidden deep import
 * is invisible until it breaks: it compiles perfectly, right up to the release
 * where the shared file it reached into has moved.
 */
function assertModuleImports(resolution) {
  if (resolution.kind !== 'distribution') return;

  const problems = verifyModuleImports(resolution.root);
  if (problems.length === 0) return;

  throw new SiteUiConfigError(
    `The Site UI module at ${resolution.root} imports modules the interface does not ` +
      `promise:\n  - ${problems.join('\n  - ')}`,
  );
}

/** Mirrors the required exports `SiteUiClientModule`/`SiteUiServerModule` declare. */
const REQUIRED_CLIENT_EXPORTS = ['descriptor'];

/**
 * `Landing`, `AuthFrame`, `TermsFrame` and `PublicFrame` are all optional, and
 * for one reason: each is an answer to a question the host asks. `Landing`,
 * `AuthFrame` and `TermsFrame` decide which routes the module owns, so an absent
 * one means the console's page stays. `PublicFrame` is not rendered by the host
 * at all — it is the module's own layout for the module's own pages — so
 * requiring it asked every module for a component nothing would call, which is
 * how the neutral module came to export a passthrough that did nothing.
 *
 * The descriptor is the one export that is required, because it is the module's
 * statement of which interface it implements. Without it there is nothing to
 * check the rest against.
 */

/**
 * The three page-owning frames are checked as optional here, because each is a
 * *claim about a whole page* rather than a piece the host can substitute: a
 * module with no `Landing` is saying the console's landing page is correct, and
 * one with no `AuthFrame` is saying its account pages sit inside the console
 * container.
 *
 * Requiring any of them would destroy the distinction the host depends on. A
 * required `AuthFrame` had to be stubbed by every module, and the neutral
 * module's stub was a card — so the boundary asked "does a frame exist?", got
 * yes, stepped aside, and left five default account pages with no header, no
 * `<main>` and no footer.
 *
 * `TermsFrame` is optional for the same reason plus one more: whether it is
 * needed depends on whether the module ships the legal text, and the build
 * cannot tell that from the export list alone, because the text is data.
 */

/**
 * The server half requires nothing.
 *
 * `metadata` and `locale` are both optional — the console's title and language
 * are the correct defaults for a module that says nothing — and the descriptor
 * lives on the client half so that the two entries cannot disagree about which
 * API revision is installed.
 */
const REQUIRED_SERVER_EXPORTS = [];

/**
 * Which names a source file exports.
 *
 * Static, because this runs in plain Node at config load: the entries are
 * TypeScript and TSX, and executing them there is impossible — `require` cannot
 * read TSX, and a client entry reaches `usePathname` through its imports at
 * module scope. Reading the export list answers the question actually being
 * asked ("did the module provide what the interface promises?") and it answers
 * it the same way for TypeScript and for JavaScript.
 *
 * Deliberately conservative: it recognises the forms this interface is written
 * in and reports anything it cannot see, so an unrecognised syntax fails the
 * build instead of passing quietly.
 */
function exportedNames(source) {
  const names = new Set();

  const declaration =
    /^\s*export\s+(?:declare\s+)?(?:async\s+)?(?:function|const|let|var|class|enum)\s+([A-Za-z0-9_$]+)/gm;
  for (const match of source.matchAll(declaration)) names.add(match[1]);

  // A default export counts as the contract's `default` name.
  if (/^\s*export\s+default\b/m.test(source)) names.add('default');

  // Named export lists, with or without a `from` clause. The `from` form
  // re-exports another module's binding, which satisfies the interface just as
  // well as a local declaration.
  for (const match of source.matchAll(/^\s*export\s*\{([^}]*)\}\s*(?:from\s*['"][^'"]+['"])?/gm)) {
    for (const raw of match[1].split(',')) {
      const trimmed = raw.trim();
      if (trimmed === '' || /^type\s/.test(trimmed)) continue;
      const alias = trimmed.split(/\s+as\s+/);
      names.add((alias[1] ?? alias[0]).trim());
    }
  }

  return names;
}

/**
 * Check that the active module can actually be compiled.
 *
 * A module can resolve and still be missing an export — a rename, a typo, a
 * file that forgot one — and that has to stop the build here rather than
 * surface as a blank page in production.
 */
function checkExports(source, file, label, required, problems) {
  const names = exportedNames(source);

  for (const name of required) {
    if (!names.has(name)) {
      problems.push(`${file} does not export \`${name}\`.`);
    }
  }
}

function assertSiteUiEntries(resolution) {
  const problems = [];

  const read = (label, file) => {
    try {
      return fs.readFileSync(file, 'utf8');
    } catch (error) {
      problems.push(`${label} entry (${file}) could not be read: ${error.message}`);
      return null;
    }
  };

  const clientSource = read('client', resolution.client);
  const serverSource = read('server', resolution.server);
  if (clientSource === null || serverSource === null) {
    throw new SiteUiConfigError(problems.join('\n'));
  }

  checkExports(clientSource, resolution.client, 'client', REQUIRED_CLIENT_EXPORTS, problems);
  checkExports(serverSource, resolution.server, 'server', REQUIRED_SERVER_EXPORTS, problems);
  checkManifestAgrees(resolution, problems);

  if (problems.length > 0) {
    throw new SiteUiConfigError(
      `The Site UI module at ${resolution.root} is not usable:\n  - ${problems.join('\n  - ')}`,
    );
  }
}

/**
 * The module's declarations have to agree with each other, and with the build.
 *
 * `manifest.json` and the client's `descriptor` are two statements of the same
 * identity, and nothing compared them: a module could declare `id`,
 * `site_ui_api` and `locale` in its manifest, export a different `id` from its
 * descriptor, and build cleanly — the resolver took the descriptor and never
 * opened the manifest at all. The image then recorded one name while the
 * manifest, which is what a reader and the release tooling see, said another.
 *
 * One truth per fact, compared rather than assumed. A disagreement is a build
 * failure because neither file can be picked as authoritative without guessing
 * which one the author meant.
 */
function checkManifestAgrees(resolution, problems) {
  if (resolution.kind === 'neutral') return;
  let document;
  let descriptor;
  try {
    document = JSON.parse(fs.readFileSync(path.join(resolution.root, 'manifest.json'), 'utf8'));
    descriptor = readDescriptor(resolution.root);
  } catch (error) {
    problems.push(`manifest.json and descriptor could not be validated: ${error.message}`);
    return;
  }
  if (!document || typeof document !== 'object' || Array.isArray(document)) {
    problems.push('manifest.json must be an object');
    return;
  }
  for (const [key, clientKey, type] of [
    ['id', 'id', 'string'],
    ['site_ui_api', 'siteUiApi', 'number'],
    ['locale', 'locale', 'string'],
  ]) {
    if (typeof document[key] !== type || typeof descriptor[clientKey] !== type) {
      problems.push(
        `manifest.json ${key} and descriptor ${clientKey} must both be ${type} literals`,
      );
    } else if (document[key] !== descriptor[clientKey]) {
      problems.push(
        `manifest.json declares ${key} '${document[key]}' but the client's descriptor declares '${descriptor[clientKey]}'`,
      );
    }
  }
  if (typeof document.id === 'string' && !/^[a-z0-9][a-z0-9_-]*$/.test(document.id)) {
    problems.push(
      'manifest.json id must contain only lowercase letters, digits, hyphens and underscores',
    );
  }
  if (document.site_ui_api !== SITE_UI_API_VERSION) {
    problems.push(
      `manifest.json declares site_ui_api ${JSON.stringify(document.site_ui_api)}; this build implements v${SITE_UI_API_VERSION}`,
    );
  }
}

module.exports = {
  SITE_UI_API_VERSION,
  SITE_UI_DIR_ENV,
  SITE_UI_API_ENV,
  GENERATED_DIR,
  NEUTRAL_DIR,
  STUB_FILE,
  TSCONFIG_FILE,
  SiteUiConfigError,
  resolveSiteUi,
  assertModuleImports,
  webpackAlias,
  vitestAlias,
  descriptorId,
  generateSiteUi,
  prepareSiteUi,
  assertSiteUiEntries,
  assertModulePresent,
};
