#!/usr/bin/env bash
# Install and configure Nginx as the public reverse proxy for freeinference.org.
#
# Requires a Cloudflare Origin Certificate already downloaded from:
#   Cloudflare Dashboard → SSL/TLS → Origin Server → Create Certificate
#
# Usage:
#   sudo ORIGIN_CERT=/path/to/origin.pem ORIGIN_KEY=/path/to/origin.key ./ops/setup/setup_nginx.sh
#
# Or with flags:
#   sudo ./ops/setup/setup_nginx.sh --cert /path/to/origin.pem --key /path/to/origin.key
#
# Re-running the script is safe (idempotent).

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

DOMAIN="${DOMAIN:-freeinference.org}"
CERT_DEST_DIR="/etc/ssl/freeinference"
NGINX_CONF_SRC="$REPO_ROOT/deploy/nginx/freeinference.conf"
NGINX_AVAILABLE="/etc/nginx/sites-available/freeinference.conf"
NGINX_ENABLED="/etc/nginx/sites-enabled/freeinference.conf"
SNIPPETS_DIR="/etc/nginx/snippets"
REAL_IP_CONF="$SNIPPETS_DIR/cloudflare-real-ip.conf"

# ── Helpers ──────────────────────────────────────────────────────────────────

log()  { printf '[setup-nginx] %s\n' "$*"; }
die()  { log "ERROR: $*" >&2; exit 1; }
info() { printf '\033[33m[setup-nginx]\033[0m %s\n' "$*"; }

# ── Argument parsing ──────────────────────────────────────────────────────────

ORIGIN_CERT="${ORIGIN_CERT:-}"
ORIGIN_KEY="${ORIGIN_KEY:-}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cert|--key)
            [[ $# -ge 2 && "$2" != --* ]] || die "Flag $1 requires a value."
            if [[ "$1" == "--cert" ]]; then
                ORIGIN_CERT="$2"
            else
                ORIGIN_KEY="$2"
            fi
            shift 2
            ;;
        *) die "Unknown argument: $1. Use --cert and --key." ;;
    esac
done

[[ -n "$ORIGIN_CERT" ]] || die "Provide the origin certificate via --cert or ORIGIN_CERT env var."
[[ -n "$ORIGIN_KEY"  ]] || die "Provide the origin private key via --key or ORIGIN_KEY env var."
[[ -f "$ORIGIN_CERT" ]] || die "Certificate file not found: $ORIGIN_CERT"
[[ -f "$ORIGIN_KEY"  ]] || die "Key file not found: $ORIGIN_KEY"
[[ $EUID -eq 0 ]] || die "Must run as root (use sudo)."

# ── 1. Install Nginx ──────────────────────────────────────────────────────────

log "Installing nginx..."
apt-get update -q
apt-get install -y nginx

# ── 2. Install certificate and key ───────────────────────────────────────────

log "Installing TLS certificate to $CERT_DEST_DIR..."
install -d -m 700 "$CERT_DEST_DIR"
install -m 600 "$ORIGIN_CERT" "$CERT_DEST_DIR/fullchain.pem"
install -m 600 "$ORIGIN_KEY"  "$CERT_DEST_DIR/privkey.pem"

# ── 3. Generate Cloudflare real-IP snippet ────────────────────────────────────
#
# All inbound connections come from Cloudflare; without this, $remote_addr is
# always a Cloudflare IP and X-Real-IP / X-Forwarded-For reach the backend
# with the wrong address (breaking rate-limiting and access logs).
#
# IP ranges: https://www.cloudflare.com/ips-v4/ and /ips-v6/

log "Generating Cloudflare real-IP snippet at $REAL_IP_CONF..."
install -d "$SNIPPETS_DIR"

# Fetch current IP ranges from Cloudflare; fall back to embedded list on failure.
CF_IPV4=""
CF_IPV6=""
if command -v curl &>/dev/null; then
    CF_IPV4="$(curl -sf --max-time 5 https://www.cloudflare.com/ips-v4/ 2>/dev/null || true)"
    CF_IPV6="$(curl -sf --max-time 5 https://www.cloudflare.com/ips-v6/ 2>/dev/null || true)"
fi

# Embedded fallback (last updated 2025-04; refresh via the URLs above)
if [[ -z "$CF_IPV4" ]]; then
    CF_IPV4="173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
104.16.0.0/13
104.24.0.0/14
172.64.0.0/13
131.0.72.0/22"
    log "  (used embedded IPv4 list — curl fetch failed or unavailable)"
fi

if [[ -z "$CF_IPV6" ]]; then
    CF_IPV6="2400:cb00::/32
2606:4700::/32
2803:f800::/32
2405:b500::/32
2405:8100::/32
2a06:98c0::/29
2c0f:f248::/32"
    log "  (used embedded IPv6 list — curl fetch failed or unavailable)"
fi

# Build the snippet in a temp file, validate each CIDR, then atomically move
# it into place. This avoids a half-written file if the script is interrupted
# and prevents malformed lines from Cloudflare ever reaching nginx.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

ipv4_re='^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
ipv6_re='^[0-9a-fA-F:]+/[0-9]{1,3}$'

{
    echo "# Cloudflare real-IP — generated by setup_nginx.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Refresh: curl https://www.cloudflare.com/ips-v4/ and /ips-v6/ then re-run setup_nginx.sh"
    echo ""
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] || continue
        [[ "$cidr" =~ $ipv4_re ]] || continue
        echo "set_real_ip_from $cidr;"
    done <<<"$CF_IPV4"
    while IFS= read -r cidr; do
        [[ -n "$cidr" ]] || continue
        [[ "$cidr" =~ $ipv6_re ]] || continue
        echo "set_real_ip_from $cidr;"
    done <<<"$CF_IPV6"
    echo ""
    echo "# Loopback: required when nginx sits behind a local cloudflared tunnel."
    echo "set_real_ip_from 127.0.0.1;"
    echo "set_real_ip_from ::1;"
    echo ""
    echo "real_ip_header CF-Connecting-IP;"
    echo "real_ip_recursive on;"
} > "$tmp"

install -m 644 "$tmp" "$REAL_IP_CONF"

# ── 4. Install nginx config ───────────────────────────────────────────────────

log "Installing nginx config (domain: $DOMAIN)..."
sed "s/freeinference\.org/$DOMAIN/g" "$NGINX_CONF_SRC" > "$NGINX_AVAILABLE"

# Remove the default site if present
rm -f /etc/nginx/sites-enabled/default

ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"

# ── 5. Test and start ─────────────────────────────────────────────────────────

log "Testing nginx config..."
nginx -t

systemctl enable nginx

if systemctl is-active --quiet nginx; then
    log "Reloading nginx..."
    systemctl reload nginx
else
    log "Starting nginx..."
    systemctl start nginx
fi

# ── 6. Smoke test ─────────────────────────────────────────────────────────────

log "Checking nginx is listening on port 443..."
if ss -tlnp | grep -q ':443 '; then
    log "OK — nginx is listening on :443."
else
    log "WARNING: port 443 does not appear to be open. Check 'systemctl status nginx'."
fi

info ""
info "Nginx setup complete for $DOMAIN."
info ""
info "Next steps:"
info "  1. Verify the site: curl -I https://$DOMAIN/"
info "  2. Confirm real client IPs appear in: tail -f /var/log/nginx/freeinference.access.log"
info "  3. To update the cert later, re-run this script with the new --cert / --key files."
