routing_strategy: fixed
routing_parameter:
  local_fraction: 0.6
timeout: 2
health_check: 30
logging:
  output: output.log
local_deployment:
  - endpoint: http://localhost:8003
    models:
      - qwen3-coder-30b
  - endpoint: http://localhost:12003
    models:
      - glm-4.6
  - endpoint: http://localhost:12004
    models:
      - minimax-m2
remote_deployment:
  - endpoint: ${CHUTES_BASE_URL}
    models:
      - qwen3-coder-30b
  - endpoint: https://api.minimax.io/v1
    models:
      - minimax-m2
  - endpoint: https://api.z.ai/api/coding/paas/v4/
    models:
      - glm-4.6
