// P0 skeleton fixtures. Replace with the Job API client once AgentJobStore and
// the /agents endpoints land (issue #1041) — the shapes in types.ts are the
// contract this UI expects from that API.

import type { AgentJob } from './types';

export const AGENT_JOBS: AgentJob[] = [
  {
    id: 'job-7f3a',
    title: 'Fix SSE total-timeout regression on /v1/messages',
    state: 'running',
    repo: 'hybridInference',
    baseSha: 'e5bd1b9',
    branch: 'agent/job-7f3a',
    runtime: 'claude-code',
    runtimeVersion: 'v2.1.34',
    model: 'qwen3.6-35b',
    modelLocal: 'H200',
    spentUsd: 0.41,
    budgetUsd: 2.0,
    elapsedLabel: '6m 12s',
    timeoutLabel: '30m',
    networkSetup: 'Trusted',
    networkAgent: 'PlatformOnly',
    sandbox: 'actions-dogfood',
    attempts: [
      {
        no: 1,
        status: 'superseded',
        note: 'Attempt 1 was superseded at 14:32 — worker lease expired after heartbeat loss; a new attempt took over. Events are read-only, preserved for audit.',
      },
      { no: 2, status: 'live' },
    ],
    events: [
      {
        kind: 'lifecycle',
        text: 'Sandbox provisioned · fs snapshot restored, setup skipped (42s)',
      },
      {
        kind: 'thinking',
        text: 'The 300s total timeout was reintroduced in the middleware reorder — the SSE exemption from #889 needs to move after the auth wrapper…',
      },
      {
        kind: 'tool_use',
        tool: 'Read',
        detail: 'apps/backend/serving/servers/middleware.py',
      },
      {
        kind: 'tool_use',
        tool: 'Bash',
        detail: 'pytest -q tests/unit/servers/test_sse_timeout.py',
        output: [
          '..F                                                    [100%]',
          'FAILED test_sse_timeout.py::test_stream_exempt_from_total_timeout',
          'assert elapsed < 300  # stream killed at total timeout',
          '1 failed, 2 passed in 4.21s',
        ],
      },
      { kind: 'egress_denied', host: 'api.segment.io:443', attempts: 3 },
      {
        kind: 'tool_use',
        tool: 'Edit',
        detail: 'apps/backend/serving/servers/middleware.py',
        diffStat: '+12 −3',
      },
      { kind: 'usage', text: 'turn 14 · 8.2k in / 640 out · cache hit 71% · $0.028' },
    ],
    liveNote: 'Claude Code is running · turn 15 · re-running the failing test',
    eventCount: 147,
    diffFiles: ['middleware.py', 'test_sse_timeout.py', 'CHANGELOG.md'],
    diffStat: { add: 38, del: 9 },
    diffLines: [
      { marker: 'hunk', text: '@@ -142,9 +142,14 @@ def build_middleware_stack(app):' },
      { marker: 'ctx', text: '     app.add_middleware(RequestIDMiddleware)' },
      { marker: 'del', text: '-    app.add_middleware(TotalTimeoutMiddleware, timeout=300)' },
      { marker: 'add', text: '+    # SSE streams are exempt from the total timeout (#865/#889):' },
      { marker: 'add', text: '+    # a healthy long generation must not be killed at 300s.' },
      { marker: 'add', text: '+    app.add_middleware(' },
      {
        marker: 'add',
        text: '+        TotalTimeoutMiddleware, timeout=300, exempt=is_sse_request',
      },
      { marker: 'add', text: '+    )' },
      { marker: 'ctx', text: '     app.add_middleware(AuthContextMiddleware)' },
    ],
    rawLines: [
      '{"attempt":2,"seq":144,"type":"tool_use","name":"Bash","input":{"command":"pytest -q tests/unit/servers/test_sse_timeout.py"}}',
      '{"attempt":2,"seq":145,"type":"tool_result","exit_code":1,"truncated":false}',
      '{"attempt":2,"seq":146,"type":"error","subtype":"egress_denied","host":"api.segment.io","port":443,"count":3}',
      '{"attempt":2,"seq":147,"type":"usage","in":8192,"out":640,"cache_read":5804,"cost_usd":0.028}',
    ],
    gates: [
      { label: 'No .github/ changes', state: 'pass' },
      { label: 'Secret scan clean', state: 'pass' },
      { label: 'Patch 18 KB', state: 'pass', detail: '/ 1 MB' },
      { label: 'format-patch check', state: 'pending', detail: 'at publish' },
    ],
    usage: { tokensIn: '184k', tokensOut: '12k', cachePct: 71, turns: 14 },
    egressDenials: 3,
  },
  {
    id: 'job-9b21',
    title: 'Bump CI Python matrix to 3.13',
    state: 'needs_review',
    stateNote: 'patch touches .github/ — held for manual release',
    repo: 'hybridInference',
    baseSha: 'e5bd1b9',
    branch: 'agent/job-9b21',
    runtime: 'codex',
    model: 'deepseek-v4-pro',
    spentUsd: 0.63,
    budgetUsd: 2.0,
    elapsedLabel: '9m 40s',
    timeoutLabel: '30m',
    networkSetup: 'Trusted',
    networkAgent: 'PlatformOnly',
    sandbox: 'actions-dogfood',
    attempts: [{ no: 1, status: 'finished' }],
    events: [
      { kind: 'lifecycle', text: 'Sandbox provisioned · setup ran from lockfile (3m 05s)' },
      { kind: 'lifecycle', text: 'Run finished · patch handed to trusted publisher' },
    ],
    eventCount: 88,
    diffFiles: ['.github/workflows/ci.yml', 'pyproject.toml'],
    diffStat: { add: 9, del: 4 },
    diffLines: [],
    rawLines: [],
    gates: [
      {
        label: '.github/ changes',
        state: 'hold',
        detail: 'workflow edits run with repo secrets on push — manual release required',
      },
      { label: 'Secret scan clean', state: 'pass' },
      { label: 'Patch 4 KB', state: 'pass', detail: '/ 1 MB' },
    ],
    usage: { tokensIn: '96k', tokensOut: '7k', cachePct: 58, turns: 9 },
    egressDenials: 0,
  },
  {
    id: 'job-4c8d',
    title: 'Add regression test for ds4 tool-call poisoning',
    state: 'done',
    repo: 'hybridInference',
    baseSha: '045ef58',
    branch: 'agent/job-4c8d',
    runtime: 'claude-code',
    model: 'claude-sonnet-5',
    spentUsd: 0.87,
    budgetUsd: 2.0,
    elapsedLabel: '18m',
    timeoutLabel: '30m',
    networkSetup: 'Trusted',
    networkAgent: 'PlatformOnly',
    sandbox: 'actions-dogfood',
    attempts: [{ no: 1, status: 'finished' }],
    events: [
      { kind: 'lifecycle', text: 'Sandbox provisioned · fs snapshot restored (40s)' },
      { kind: 'lifecycle', text: 'Draft PR #1044 opened on agent/job-4c8d' },
    ],
    eventCount: 214,
    diffFiles: ['test_anthropic_translator.py'],
    diffStat: { add: 214, del: 38 },
    diffLines: [],
    rawLines: [],
    gates: [
      { label: 'No .github/ changes', state: 'pass' },
      { label: 'Secret scan clean', state: 'pass' },
      { label: 'Patch 61 KB', state: 'pass', detail: '/ 1 MB' },
      { label: 'format-patch check', state: 'pass' },
    ],
    usage: { tokensIn: '412k', tokensOut: '31k', cachePct: 77, turns: 26 },
    egressDenials: 0,
    prLabel: 'draft PR #1044',
  },
  {
    id: 'job-4c8e',
    title: 'ds4 test · qwen3.6 comparison run',
    state: 'done',
    stateNote: 'clone · model comparison',
    repo: 'hybridInference',
    baseSha: '045ef58',
    branch: 'agent/job-4c8e',
    runtime: 'claude-code',
    model: 'qwen3.6-35b',
    modelLocal: 'H200',
    spentUsd: 0.09,
    budgetUsd: 2.0,
    elapsedLabel: '24m',
    timeoutLabel: '30m',
    networkSetup: 'Trusted',
    networkAgent: 'PlatformOnly',
    sandbox: 'actions-dogfood',
    attempts: [{ no: 1, status: 'finished' }],
    events: [
      { kind: 'lifecycle', text: 'Sandbox provisioned · fs snapshot restored (38s)' },
      { kind: 'lifecycle', text: 'Draft PR #1045 opened on agent/job-4c8e' },
    ],
    eventCount: 241,
    diffFiles: ['test_anthropic_translator.py'],
    diffStat: { add: 198, del: 41 },
    diffLines: [],
    rawLines: [],
    gates: [
      { label: 'No .github/ changes', state: 'pass' },
      { label: 'Secret scan clean', state: 'pass' },
      { label: 'Patch 58 KB', state: 'pass', detail: '/ 1 MB' },
      { label: 'format-patch check', state: 'pass' },
    ],
    usage: { tokensIn: '388k', tokensOut: '29k', cachePct: 74, turns: 31 },
    egressDenials: 0,
    prLabel: 'draft PR #1045',
  },
  {
    id: 'job-1d5f',
    title: 'Migrate api_logs export to Parquet',
    state: 'failed',
    stateNote: 'budget exceeded · $2.00 cap',
    repo: 'hybridInference',
    baseSha: 'd966a24',
    branch: 'agent/job-1d5f',
    runtime: 'codex',
    model: 'kimi-k3',
    spentUsd: 2.0,
    budgetUsd: 2.0,
    elapsedLabel: '27m',
    timeoutLabel: '30m',
    networkSetup: 'Trusted',
    networkAgent: 'PlatformOnly',
    sandbox: 'actions-dogfood',
    attempts: [{ no: 1, status: 'finished' }],
    events: [
      { kind: 'lifecycle', text: 'Sandbox provisioned · setup ran from lockfile (2m 48s)' },
      { kind: 'lifecycle', text: 'Job stopped: budget cap reached ($2.00) — no patch published' },
    ],
    eventCount: 302,
    diffFiles: [],
    diffLines: [],
    rawLines: [],
    gates: [],
    usage: { tokensIn: '740k', tokensOut: '52k', cachePct: 49, turns: 41 },
    egressDenials: 1,
  },
  {
    id: 'job-a0c2',
    title: 'Document AgentJobStore schema in developer docs',
    state: 'queued',
    repo: 'hybridInference',
    baseSha: 'e5bd1b9',
    branch: 'agent/job-a0c2',
    runtime: 'claude-code',
    model: 'glm-5',
    spentUsd: 0,
    budgetUsd: 2.0,
    timeoutLabel: '30m',
    networkSetup: 'Trusted',
    networkAgent: 'PlatformOnly',
    sandbox: 'actions-dogfood',
    attempts: [],
    events: [{ kind: 'lifecycle', text: 'Queued · waiting for a runner slot' }],
    eventCount: 1,
    diffFiles: [],
    diffLines: [],
    rawLines: [],
    gates: [],
    usage: { tokensIn: '0', tokensOut: '0', cachePct: 0, turns: 0 },
    egressDenials: 0,
  },
];

export function getAgentJob(id: string): AgentJob | undefined {
  return AGENT_JOBS.find((job) => job.id === id);
}
