"""The allowlist proxy that makes the Trusted egress tier real (issue #1041).

The tiers in :mod:`serving.agent_jobs.egress` are networks. ``platform_only``
needs nothing else — an internal network reaches the gateway and stops. Any
tier above it needs something on that network with a second leg, and this is
it: a Squid instance that accepts CONNECT for an allowlisted host and refuses
everything else.

**Why a proxy rather than a firewall on the network.** The sandbox names its
destination in the CONNECT request, so an allowlist is a string comparison
against the name the client actually asked for. Filtering by address instead
means resolving a domain to a set of IPs that a CDN rotates under you, and
being wrong in the direction that breaks installs.

**Why we do not terminate TLS.** A CONNECT line carries the target host in the
clear, which is everything an allowlist needs. Intercepting the session would
put the proxy in a position to read a repository's traffic, which is a strictly
worse thing to have on the network than the sandbox it polices.

**Why the config is generated here rather than written by hand.** The allowlist
is interpolated into a config file that decides what an untrusted sandbox may
reach. A domain carrying a newline would append directives of its own, so the
values are validated (in :func:`serving.agent_jobs.egress.normalize_domains`)
before they can reach this renderer, and the renderer refuses anything that
slipped through. Hand-editing the config is how that check gets skipped.

Run as a module to produce the file the proxy container starts from::

    python -m serving.agent_jobs.egress_proxy --out /etc/squid/generated/squid.conf
"""

from __future__ import annotations

import argparse
import os
import sys

from serving.agent_jobs.egress import (
    EgressPolicyError,
    check_allowlist,
    normalize_domains,
    trusted_domains,
)

DEFAULT_PROXY_PORT = 3128

# A host the sandbox may never reach, used by the runner's preflight to prove
# the proxy is denying rather than merely unreachable. `.invalid` is reserved
# by RFC 2606 and resolves nowhere, so the probe cannot accidentally succeed
# against a real service even if the allowlist were wrong.
CANARY_HOST = "egress-canary.invalid"


def render_squid_config(
    domains: tuple[str, ...] | list[str],
    *,
    port: int = DEFAULT_PROXY_PORT,
) -> str:
    """Render the proxy configuration for one allowlist.

    The result denies by default: the last rule is ``http_access deny all``,
    and every allowance above it is qualified by both the destination and the
    method. Squid evaluates these in order and stops at the first match.
    """
    checked = normalize_domains(list(domains))
    check_allowlist(list(checked))
    if not checked:
        raise EgressPolicyError(
            "an allowlist proxy with no domains would deny every request, which is "
            "the platform_only tier with extra machinery. Configure domains, or "
            "select the closed tier."
        )
    if not 1 <= port <= 65535:
        raise EgressPolicyError(f"{port} is not a port")

    acl_lines = "\n".join(f"acl allowed_domains dstdomain {domain}" for domain in checked)
    return f"""\
# Generated by serving.agent_jobs.egress_proxy — do not edit.
#
# This file is the Trusted egress tier. Everything the agent sandbox is allowed
# to reach off this host is named below; everything else meets `deny all`.

http_port {port}

# Structured, one line per request, to stdout — so a denied request is visible.
# `internal: true` networks reject a connection silently, which left the design's
# "record refused egress attempts" with nowhere to observe from. The proxy is
# both the enforcement point and the only place that sees the attempt.
logformat agent ts=%ts.%03tu src=%>a verdict=%Ss/%03>Hs method=%rm target="%>ru" bytes=%<st
access_log stdio:/dev/stdout agent
cache_log stdio:/dev/stderr
pid_filename none

# No caching, ever. One cache shared by every job is a channel between tenants:
# a response fetched for one repository's install would be served to another's.
cache deny all

# Say nothing about the client upstream. Without these, a registry sees the
# sandbox's address and our forwarding chain, which is a detail about a
# customer's job that has no business leaving the host.
via off
forwarded_for delete
httpd_suppress_version_string on
icp_port 0

acl SSL_ports port 443
acl CONNECT method CONNECT
{acl_lines}

# Order matters; Squid stops at the first matching rule.
#
# 1. Anything not on the list is refused, whatever the method.
# 2. A tunnel may only be opened to 443. CONNECT to an arbitrary port would
#    turn this into a general-purpose relay for an allowlisted *name*.
# 3. Allowed: a tunnel to a listed host.
# 4. Everything else — plain HTTP included. Package managers use HTTPS, and a
#    cleartext fetch of a dependency is not something to quietly permit.
http_access deny !allowed_domains
http_access deny CONNECT !SSL_ports
http_access allow CONNECT allowed_domains
http_access deny all
"""


def build_config_from_env(env: dict[str, str] | None = None) -> str:
    """Render the config this deployment's environment describes.

    The proxy serves the Trusted tier, whose domains are the built-in registry
    list plus ``AGENT_EGRESS_ALLOWLIST``. A Custom-tier deployment supplies its
    own proxy by definition, so it is not rendered here.
    """
    source = env if env is not None else dict(os.environ)
    # Parses the operator's comma-separated string into entries; the union with
    # the built-ins happens in `trusted_domains`, which validates again. The
    # second pass is idempotent, and splitting here is not optional — handing a
    # raw string to a function that splats it would spread it character by
    # character.
    extra = normalize_domains(source.get("AGENT_EGRESS_ALLOWLIST") or "")
    try:
        port = int(source.get("AGENT_EGRESS_PROXY_PORT") or DEFAULT_PROXY_PORT)
    except ValueError as exc:
        raise EgressPolicyError(
            f"AGENT_EGRESS_PROXY_PORT={source.get('AGENT_EGRESS_PROXY_PORT')!r} is not a number"
        ) from exc
    # The same function the runner's policy uses, so the list this proxy
    # enforces cannot drift from the one the platform believes it configured.
    return render_squid_config(trusted_domains(extra), port=port)


def main(argv: list[str] | None = None) -> int:
    """Write the proxy configuration, or explain why it cannot be written."""
    parser = argparse.ArgumentParser(description="Render the agent egress proxy configuration.")
    parser.add_argument("--out", required=True, help="path to write the configuration to")
    args = parser.parse_args(argv)

    try:
        config = build_config_from_env()
    except EgressPolicyError as exc:
        # Non-zero, and loud: the proxy container starts from this file, and a
        # deployment that renders an empty or rejected config must not go on to
        # start a proxy whose behaviour nobody chose.
        print(f"egress proxy configuration refused: {exc}", file=sys.stderr)
        return 2

    out = args.out
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(config)
    print(f"wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":  # pragma: no cover - module entrypoint
    raise SystemExit(main())
